### ISSUE TITLE
have an issue

### ISSUE THREAD

**Issue by woaphone** [xiaomi-mt6789-devs/android_device_xiaomi_yunluo#1]
[ 99% 1216/1217] finishing build rules ...
FAILED: 
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd_noaidl (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: "wpa_supplicant (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm64) missing libwifi-hal-mt66xx (STATIC_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm) missing libwifi-hal-mt66xx (STATIC_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1126: error: exiting from previous errors.
05:24:38 ckati failed with: exit status 1

#### failed to build some targets (01:08 (mm:ss)) ####

can,t build

**Comment by woaphone** [comment]
and when i breakfast yunluo and brunch yunluo has an error expr: 语法错误：未预期的参数 "5"
expr: syntax error: unexpected argument '5'

**Comment by Woomymy** [comment]
> [ 99% 1216/1217] finishing build rules ...
> FAILED: 
> external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd_noaidl (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: "wpa_supplicant (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm64) missing libwifi-hal-mt66xx (STATIC_LIBRARIES android-arm64)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm) missing libwifi-hal-mt66xx (STATIC_LIBRARIES android-arm)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> build/make/core/main.mk:1126: error: exiting from previous errors.
> 05:24:38 ckati failed with: exit status 1
> 
> #### failed to build some targets (01:08 (mm:ss)) ####
> 
> can,t build

Clone https://github.com/nashc-dev/android_hardware_mediatek_wlan to hardware/mediatek/wlan

**Comment by woaphone** [comment]
> > [ 99% 1216/1217] finishing build rules ...
> > FAILED:
> > external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)"
> > You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> > external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd_noaidl (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)"
> > You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> > external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: "wpa_supplicant (EXECUTABLES android-arm64) missing lib_driver_cmd_mt66xx (STATIC_LIBRARIES android-arm64)"
> > You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> > frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm64) missing libwifi-hal-mt66xx (STATIC_LIBRARIES android-arm64)"
> > You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> > frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm) missing libwifi-hal-mt66xx (STATIC_LIBRARIES android-arm)"
> > You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
> > build/make/core/main.mk:1126: error: exiting from previous errors.
> > 05:24:38 ckati failed with: exit status 1
> > #### failed to build some targets (01:08 (mm:ss))
> > can,t build
> 
> Clone https://github.com/nashc-dev/android_hardware_mediatek_wlan to hardware/mediatek/wlan

it can works

**Comment by woaphone** [comment]
but i have a new issue 
Fetch 'out/target/product/yunluo/system/etc/vintf/compatibility_matrix.3.xml': OK
List 'out/target/product/yunluo/system_ext/etc/vintf/': OK
Fetch 'out/target/product/yunluo/system_ext/etc/vintf/manifest.xml': OK
List 'out/target/product/yunluo/product/etc/vintf/': NAME_NOT_FOUND
The following HALs in device manifest are not declared in FCM <= level 6: 
  android.hardware.bluetooth.audio.IBluetoothAudioProviderFactory/default (@2)
  android.hardware.drm.IDrmFactory/clearkey (@1)
  android.hardware.health.IHealth/default (@1)
  android.hardware.sensors.ISensors/default (@1)
  android.hardware.wifi.hostapd.IHostapd/default (@1)
  android.hardware.wifi.supplicant.ISupplicant/default (@1)
  android.hardware.wifi@1.6::IWifi/default
  vendor.lineage.health.IChargingControl/default (@1)
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix: 
    vendor.lineage.health.IChargingControl/default (@1)
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 6.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 6 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

**Comment by Woomymy** [comment]
Oh, my bad, as I'm always building updatepackage, i forgot to `check-vintf-all`, just cherry-pick https://github.com/xiaomi-mt6781-devs/android_device_xiaomi_viva/commit/ede4b670fd7936c3b085ba66b480bd873647e1fc
