### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mgaerttner** [xiaomi-mt6789-devs/android_device_xiaomi_yunluo#5]
Sorry for opening this here (github noob). I have a China yunuo running China 14.0.7.0.TLYCNXM. My bootloader is OEM unlocked. Am I safe to install or is the Global ROM a hard requirement? Thanks in advance.

**Comment by Woomymy** [comment]
Global ROM is an hard requirement

**Comment by mgaerttner** [comment]
> Global ROM is an hard requirement

Thanks for the confirmation. I'm a wuss, but I finally broke down and manually installed the Global ROM. FYI, if anyone else with the China version of the yunluo is in the same boat, I was able to grab the fastboot ROM, extract it, and then just run the flash_all.sh script and let fastboot do its thing. Had to OEM unlock first obviously, but it worked without any trouble.
