### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by Ziggy815** [xiaomi-mt6789-devs/android_device_xiaomi_yunluo#6]
Hi there, 

i am trying to compile this under LOS20, latest repo sync.
When i use your local_manifest, i get an Error, when i remove the "remove project" line, that works so far.
Then i do as normal : 

. build/envsetup.sh
breakfast lineage_yunluo-eng
brunch lineage_yunluo-eng

then the following error occurs and compiling stops : 

$(shell date -u +%Y%m%d) was changed, regenerating...
Adding CUSTOM_LOCALES [ast_ES gd_GB cy_GB fur_IT] to PRODUCT_LOCALES [en_US en_US af_ZA am_ET ar_EG ar_XB as_IN az_AZ be_BY bg_BG bn_BD bs_BA ca_ES cs_CZ da_DK de_DE el_GR en_AU en_CA en_GB en_IN en_XA es_ES 
es_US et_EE eu_ES fa_IR fi_FI fr_CA fr_FR gl_ES gu_IN hi_IN hr_HR hu_HU hy_AM in_ID is_IS it_IT iw_IL ja_JP ka_GE kk_KZ km_KH kn_IN ko_KR ky_KG lo_LA lt_LT lv_LV mk_MK ml_IN mn_MN mr_IN ms_MY my_MM nb_NO ne_N
P nl_NL or_IN pa_IN pl_PL pt_BR pt_PT ro_RO ru_RU si_LK sk_SK sl_SI sq_AL sr_Latn_RS sr_RS sv_SE sw_TZ ta_IN te_IN th_TH tl_PH tr_TR uk_UA ur_PK uz_UZ vi_VN zh_CN zh_HK zh_TW zu_ZA en_XC]
[100% 2/2] initializing build system ...
Adding CUSTOM_LOCALES [ast_ES gd_GB cy_GB fur_IT] to PRODUCT_LOCALES [en_US en_US af_ZA am_ET ar_EG ar_XB as_IN az_AZ be_BY bg_BG bn_BD bs_BA ca_ES cs_CZ da_DK de_DE el_GR en_AU en_CA en_GB en_IN en_XA es_ES 
es_US et_EE eu_ES fa_IR fi_FI fr_CA fr_FR gl_ES gu_IN hi_IN hr_HR hu_HU hy_AM in_ID is_IS it_IT iw_IL ja_JP ka_GE kk_KZ km_KH kn_IN ko_KR ky_KG lo_LA lt_LT lv_LV mk_MK ml_IN mn_MN mr_IN ms_MY my_MM nb_NO ne_N
P nl_NL or_IN pa_IN pl_PL pt_BR pt_PT ro_RO ru_RU si_LK sk_SK sl_SI sq_AL sr_Latn_RS sr_RS sv_SE sw_TZ ta_IN te_IN th_TH tl_PH tr_TR uk_UA ur_PK uz_UZ vi_VN zh_CN zh_HK zh_TW zu_ZA en_XC]
[ 99% 187/188] finishing build rules ...
FAILED: 
build/make/core/main.mk:1312: warning:  device/xiaomi/yunluo/lineage_yunluo.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
android.hardware.usb-service.mediatek
rebalance_interrupts-vendor.mediatek
build/make/core/main.mk:1312: error: Build failed.
01:16:34 ckati failed with: exit status 1

#### failed to build some targets (03:07 (mm:ss)) ####

Would be nice if you can help me.

**Comment by Woomymy** [comment]
Use this org's hw/mediatek

**Comment by Ziggy815** [comment]
> Use this org's hw/mediatek

I am using those already, as i wrote i use your local_manifest for it. 
Also tried to delete the hardware/mediatek folder and did a manual clone of your git, same error, also tried with org. lineageos and nashrc mediatek folder nothing compiles.
I am trying on a complete fresh synced LOS20 source without any additions. Just that and your local manifestfile.
Btw. when i am trying your hardware/mediatek i also have to delete device/xiaomi/yunluo/libmtkperf_client or i get another error

**Comment by Ziggy815** [comment]
So gave it a complete new try : 

make clean clobber
rm -rf hardware/ device/ vendor/
cat .repo/local_manifests/mt6789.xml

<manifest>
    
    <remote name="6789-dev" fetch="https://github.com/xiaomi-mt6789-devs" revision="lineage-20" />
    <remote name="lineageos" fetch="https://github.com/LineageOS" revision="lineage-20" />
    <remote name="nashc-dev" fetch="https://github.com/nashc-dev" revision="lineage-20" />

    
    <project path="device/xiaomi/yunluo" name="android_device_xiaomi_yunluo" remote="6789-dev" />
    <project path="device/xiaomi/yunluo-kernel" name="android_device_xiaomi_yunluo-kernel" remote="6789-dev" />

    <project path="device/mediatek/sepolicy_vndr" name="android_device_mediatek_sepolicy_vndr" remote="6789-dev" />

    
    <project path="hardware/xiaomi" name="android_hardware_xiaomi" remote="lineageos" />

    <project path="hardware/mediatek" name="android_hardware_mediatek" remote="6789-dev" />
	<project path="hardware/mediatek/wlan" name="android_hardware_mediatek_wlan" remote="nashc-dev" /> 

    
    <project path="vendor/xiaomi/yunluo" name="android_vendor_xiaomi_yunluo" remote="6789-dev" />
</manifest>

repo sync

with this i should shurely use only your manifest in a fresh los20 source

. build/envsetup.sh
brunch lineage_yunluo-eng

In file included from build/make/core/soong_cc_rust_prebuilt.mk:54:
build/make/core/base_rules.mk:338: error: hardware/mediatek/libmtkperf_client: MODULE.TARGET.SHARED_LIBRARIES.libmtkperf_client already defined by device/xiaomi/yunluo/libmtkperf_client.
17:51:01 ckati failed with: exit status 1

#### failed to build some targets (03:20 (mm:ss)) ####

so i delete device/xiaomi/yunluo/libmtkperf_client/

rm device/xiaomi/yunluo/libmtkperf_client/ -rf

make clean clobber
brunch lineage_yunluo-eng

and again : 
[ 99% 584/585] finishing build rules ...
FAILED: 
build/make/core/main.mk:1312: warning:  device/xiaomi/yunluo/lineage_yunluo.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
android.hardware.usb-service.mediatek
rebalance_interrupts-vendor.mediatek
build/make/core/main.mk:1312: error: Build failed.
17:56:36 ckati failed with: exit status 1

#### failed to build some targets (03:51 (mm:ss)) ####

**Comment by Ziggy815** [comment]
Hey :)

So .. i did a little testing the last couple of days.

The sources, like they are with the Oct. Updates will not compile! Not with the Hardware and vendor from here, or Los or nashrc.

I rolled back to commit ca6aa190acbeed7f83dfc3f04e7e7bb6856a6c70 for the Device Tree and commit 4009dd710fa67c1daa65194aade028af17043334 for the vendor tree, with those it compiles and runs without problems with 
the actual Los20 sources.

I dont know what one needs to compile the Sources after that commit but its not on this repository, maybe some of you have forgotten to push a commit thats local or to update the vendor tree.

Hope that helps.

Greetings
Zig.

**Comment by Ziggy815** [comment]
Seems nobody realy gives a shit

**Comment by Woomymy** [comment]
Seems like I didn't push, sorry, I'll do it when I have time.

**Comment by Ziggy815** [comment]
> Seems like I didn't push, sorry, I'll do it when I have time.

Thanks and sorry for my harsh language! I was just frustrated that nobody answered

**Comment by Woomymy** [comment]
Everything should be pushed now

**Comment by Woomymy** [comment]
Everything should be pushed now

**Comment by Ziggy815** [comment]
> Everything should be pushed now

Thank you very much, works like a charm!

Greetings
Zig.
